config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :overtime_work_infos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/overtime_work_info.rb
class OvertimeWorkInfo < ApplicationRecord
  belongs_to :user
  has_many :work_member

  attr_reader :member_infos, :error_message

  def initialize(params)
    @job_num = params[:job_num]
    @reason = params[:reason]
    @leader_user_id = params[:leader_user_id]
    @user_id = params[:user_id]

    super
  end

  def request_create!(member_infos)
    @member_infos = member_infos

    begin
      ActiveRecord::Base.transaction do
        self.save!
        create_work_member_info
      end
    rescue => e
      @error_message = 'データが正しくありません。'
    end
  end

  def request_judge_authority?(user_id)
    return true if leader?(user_id) && leader_judge_status.nil?
    return true if manager?(user_id)
    
    false
  end

  def request_update(judge_info_map)
    user_id = judge_info_map[:current_user_id]
    manager_id = judge_info_map[:manager_user_id]
    judge = judge_info_map[:judge]

    set_manger_user_id(manager_id)
    change_judge_status(user_id, judge)
    
    @error_message = 'データの更新に失敗しました。' unless save
  end

  def start_time
    work_member.order(start_time: "ASC").first.start_time.strftime('%Y年%m月%d日 %H時%M分')
  end

  def end_time
    work_member.order(end_time: "ASC").first.end_time.strftime('%Y年%m月%d日 %H時%M分')
  end

  private

  # REFACTOR: 最終判断者かリーダー判断かのみを条件文にして、他の比較については別途切り出したい
  def change_judge_status(user_id, judge)
    if leader?(user_id) && leader_judge_status.nil? && manager_user_id.nil?
      ultimate_judge_status = judge
    elsif leader?(user_id) && leader_judge_status.nil? && manager_user_id.present?
      leader_judge_status = judge
    elsif manager?(user_id) && ultimate_judge_status.nil?
      ultimate_judge_status = judge
    end
  end

  def set_manger_user_id(manager_id)
    manager_user_id = manager_id
  end

  #NOTE: 最終的に最大何件送られてくるかは2023年8/16時点では決まってない
  def user_ids
    user_ids = []

    (1..5).each do |i|
      break if member_infos["user_id_#{i}"].nil?
      user_ids.push(member_infos["user_id_#{i}"])
    end

    user_ids
  end

  def create_work_member_info
    start_time = WorkMember.normalize_datetime(member_infos[:start_time_list])
    end_time = WorkMember.normalize_datetime(member_infos[:end_time_list])

    user_ids.each do |id|
      work_member_info_map = { :user_id => id, :start_time => start_time, :end_time => end_time, :overtime_work_info_id => self.id }
      WorkMember.new(work_member_info_map).save!
    end

    raise # 保存させないため一時的に。
  end

  def leader?(user_id)
    return user_id == leader_user_id
  end

  def manager?(user_id)
    return user_id == manager_user_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work_member.rb
class WorkMember < ApplicationRecord
  belongs_to :user
  belongs_to :overtime_work_info

  def initialize(info_map)
    @user_id = info_map[:user_id]
    @overtime_work_info_id = info_map[:overtime_work_info_id]
    @start_time = info_map[:start_time]
    @end_time = info_map[:end_time]

    super
  end

  def self.normalize_datetime(time_list)
    time = time_list[0]
    yymmdd = time.values[0..2].join('-')
    hhmm = time.values[3..4].join(':')

    "#{yymmdd} #{hhmm}".to_datetime
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    overtime_work_infos_path
  end
end

app/controllers/overtime_work_infos_controller.rb
class OvertimeWorkInfosController < ApplicationController
  def index
    @overtime_work_infos = OvertimeWorkInfo.paginate(page: params[:page], per_page: 5)
  end

  def show
    @overtime_work_info = OvertimeWorkInfo.find(params[:id])
    @admin = @overtime_work_info.request_judge_authority?(current_user.id)
  end

  def new
    all_user = User.select(:id, :user)
    @admin_users = all_user.where(admin: true).pluck(:name, :id)
    @users = all_user.pluck(:name, :id)
  end

  def edit
    @overtime_work_info = OvertimeWorkInfo.find(params[:id])
    @admin_users = User.where(admin: true).pluck(:name, :id)
  end

  def create
    overtime_work_info = OvertimeWorkInfo.new(overtime_work_info_params)
    overtime_work_info.request_create!(work_member_params)

    respond_to do |format|
      if overtime_work_info.error_message.nil?
        format.html { redirect_to overtime_work_info, notice: "残業申請を作成しました。" }
      else
        format.html { redirect_to new_overtime_work_info_path, notice: "残業申請に失敗しました。" }
      end
    end
  end

  # 承認 / 却下押下時にステータスを変更する処理をいれる
  # リーダが許可/却下した場合、リーダはedit画面を表示できないようにする
  # 部門長が許可/却下した場合、部門長はedit画面を表示できないようにする
  # 理由を記述するフォームを生成する
  def update
    overtime_work_info = OvertimeWorkInfo.find(params[:id])
    overtime_work_info.request_update(update_params)

    respond_to do |format|
      if overtime_work_info.error_message.nil?
        format.html { redirect_to overtime_work_info, notice: "残業申請を作成しました。" }
      else
        format.html { redirect_to new_overtime_work_info_path, notice: "残業申請に失敗しました。" }
      end
    end
  end

  private

  def overtime_work_info_params
    params.require(:overtime_work_info).permit(:job_num, :reason, :leader_user_id).merge(user_id: current_user.id)
  end

  
  def work_member_params
    params.require(:overtime_work_info).permit(:user_id, start_time_list: datetime_keys, end_time_list: datetime_keys).merge(user_ids)
  end

  def update_params
    params.require(:judge_infos).permit(:manager_user_id, :reject_reason).merge(params.permit(:judge)).merge({ :current_user_id => current_user.id })
  end

  # REFACTOR: 本当はviewから配列で値を送るのが望ましいと思うが、selectタグを使用している場合は単数であることをRailsが期待しているため、うまく動かない。
  # 何か良い解決方法があれば...
  def user_ids
    params.require(:overtime_work_info).permit(:user_id_1, :user_id_2, :user_id_3, :user_id_4, :user_id_5)
  end

  # REFACTOR: 本当はFormクラスでAttributeAssignmentを定義したい
  def datetime_keys
    return ["(1i)", "(2i)", "(3i)", "(4i)", "(5i)"]
  end
end

app/controllers/work_members_controller.rb
class WorkMembersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/overtime_work_infos_helper.rb
module OvertimeWorkInfosHelper
end

app/helpers/work_members_helper.rb
module WorkMembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkRequestManage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/overtime_work_infos/edit.html.erb
<p>JobNo: <%= @overtime_work_info.job_num %><br></p>

<p>対象者</p>
<% @overtime_work_info.work_member.each do |member| %>
  <p><%= member.user.name %></p>
  <p><%= member.start_time.strftime('%Y年%m月%d日 %H時%M分') %> ~ <%= member.end_time.strftime('%Y年%m月%d日 %H時%M分') %></p>
<% end %>

<p>理由</p>
<%= @overtime_work_info.reason %>

<p>ステータス: <%= @overtime_work_info.ultimate_judge_status %></p>

# 承認と却下ボタンの表示を条件分岐させて、それらが正常に機能しているかテストする
<%= form_with model: @overtime_work_info, scope: :judge_infos do |f| %>
  <%= f.label :部門長, {class: 'form-label'} %>
  <%= f.select :manager_user_id, @admin_users, include_blank: "部門長を選択して下さい(任意)" %><br>

  <%= f.label :却下理由, {class: 'form-label'} %>
  <%= f.text_field :reject_reason, :class => 'form-control' %><br>

  <%= f.submit "承認", name: :judge, value: "承認" %>
  <%= f.submit "却下", name: :judge, value: "却下" %>
<% end %>


<% if @overtime_work_info.reject_reason.present? %>
  <p>却下理由</p>
  <%= @overtime_work_info.reject_reason %>
<% end %>

app/views/overtime_work_infos/index.html.erb
<%= button_to "新規申請作成", new_overtime_work_info_path, method: :get %>

<body>
  <%= yield %>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">申請者</th>
        <th scope="col">残業開始日時</th>
        <th scope="col">残業終了日時</th>
        <th scope="col">詳細</th>
        <th scope="col">ステータス</th>
      </tr>
    </thead>

    <tbody>
      <% @overtime_work_infos.each do |info| %>
        </tr>
          <th scope="row"><%= info.id %></th>
          <td><%= info.user.name %></td>
          <td><%= info.start_time %></td>
          <td><%= info.end_time %></td>
          <td><%= link_to "詳細", overtime_work_info_path(info.id) %></td>
          <td><%= info.ultimate_judge_status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @overtime_work_infos %>
</body>

app/views/overtime_work_infos/new.html.erb
<div class="row">
  <div class="col-md-6 mx-auto">
    <div class="mb-3">
      <%= form_with url: '/overtime_work_infos', scope: :overtime_work_info do |f| %>
        <div class="form-group">
          <%= f.label :job_num, "ジョブ番号", class: 'form-label' %>
          <%= f.text_field :job_num, class: 'form-control', placeholder: 'ジョブ番号を入力してください' %>
        </div>

        <% (1..2).each do |i| %>
          <% user_id = "user_id_#{i}".to_sym %>

          <div class="form-group">
            <%= f.label user_id, "対象者", class: 'form-label' %>
            <%= f.select user_id, @users, { include_blank: "対象者を選択してください" }, class: 'form-control' %>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :start_time, "開始時間", class: 'form-label' %>
          <%= f.datetime_select "start_time_list[]", { class: 'form-control' } %>
        </div>

        <div class="form-group">
          <%= f.label :end_time, "終了時間", class: 'form-label' %>
          <%= f.datetime_select "end_time_list[]", { class: 'form-control' } %>
        </div>

        <div class="form-group">
          <%= f.label :reason, "理由", class: 'form-label' %>
          <%= f.text_field :reason, class: 'form-control', placeholder: '理由を入力してください' %>
        </div>

        <div class="form-group">
          <%= f.label :leader_user_id, "承認者", class: 'form-label' %>
          <%= f.select :leader_user_id, @admin_users, { include_blank: "承認者を選択して下さい" }, class: 'form-control' %>
        </div>

        <%= f.submit "申請", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/overtime_work_infos/show.html.erb
<p>JobNo: <%= @overtime_work_info.job_num %><br></p>

<p>対象者</p>
<% @overtime_work_info.work_member.each do |member| %>
  <p><%= member.user.name %></p>
  <p><%= member.start_time.strftime('%Y年%m月%d日 %H時%M分') %> ~ <%= member.end_time.strftime('%Y年%m月%d日 %H時%M分') %></p>
<% end %>

<p>理由</p>
<%= @overtime_work_info.reason %>

<p>ステータス: <%= @overtime_work_info.ultimate_judge_status %></p>

  <% if @admin %>
    <%= link_to "申請情報の編集", edit_overtime_work_info_path %>
  <% end %>

<% if @overtime_work_info.reject_reason.present? %>
  <p>却下理由</p>
  <%= @overtime_work_info.reject_reason %>
<% end %>